Add directories required, dockerfiles, and update the readme
playasoft/volunteers pull request #199
Opened 2020-10-05 18:34 UTC by halfwit

This PR is not quite ready yet, but this serves well for documenting progress.

2020-10-05 18:37 UTC, halfwit commented
**TODO:**
- The MYSQL environment is currently set via named files in /var/secrets, but presently there is nothing being populated.

- nginx only runs on port 
  - Need to document certificate creation, and update the dockerfiles to put them where they need to go

- the mysql conf will need some updates, cc @itsrachelfish

2020-10-28 21:30 UTC, halfwit commented
Hey @itsrachelfish, would be probably sane to squash all this on the merge

2020-11-13 19:41 UTC, halfwit commented
Putting back into draft until this is thoroughly tested with the Let's Encrypt bits added in.

2020-11-23 22:09 UTC, halfwit commented
As is, this should work perfectly. I'd love to have a few people test run this, before merging.

2020-11-24 01:12 UTC, itsrachelfish requested changes

2020-11-24 01:12 UTC, itsrachelfish commented on .env
>  APP_ENV=local
The .env file is supposed to be gitignored

2020-11-24 01:16 UTC, itsrachelfish commented on docker-compose.yml
> +      ONLY_SUBDOMAINS: "true"
Does this mean using the volunteer database without a subdomain is not supported?

2020-12-04 22:02 UTC, halfwit commented
@itsrachelfish Ready for final review.

2020-12-10 11:23 UTC, itsrachelfish approved these changes
Wow, it really has never been easier to set up this project!

2020-12-10 11:23 UTC, merged